;;; edger-test.el --- Focused editor edge tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'edger)

(ert-deftest edger-default-and-custom-keys ()
  (unwind-protect
      (progn
        (should (eq (lookup-key edger-mode-map (kbd "M-h")) 'edger-left))
        (should (eq (lookup-key edger-mode-map (kbd "M-H")) 'edger-resize-left))
        (should (eq (lookup-key edger-mode-map (kbd "M-u")) 'edger-horizontal))
        (should (eq (lookup-key edger-mode-map (kbd "M-i")) 'edger-vertical))
        (should (eq (lookup-key edger-mode-map (kbd "M-w")) 'edger-close))
        (edger-setup "C" "s" "v" "q")
        (should (eq (lookup-key edger-mode-map (kbd "C-h")) 'edger-left))
        (should (eq (lookup-key edger-mode-map (kbd "C-S-h")) 'edger-resize-left))
        (should (eq (lookup-key edger-mode-map (kbd "C-s")) 'edger-horizontal))
        (should-not (lookup-key edger-mode-map (kbd "M-u")))
        (edger-setup "C-M")
        (should (eq (lookup-key edger-mode-map (kbd "C-M-S-l")) 'edger-resize-right)))
    (edger-setup)))

(ert-deftest edger-local-then-cross ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((left (selected-window))
           (right (split-window-right))
           (frame (selected-frame))
           calls)
      (should (file-executable-p edger-executable))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "w1:p2")
            (set-frame-parameter frame 'edger-herdr-socket-path "/tmp/herdr.sock")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args)
                         (push (list args (getenv "HERDR_SOCKET_PATH")
                                     (getenv "HERDR_PANE_ID")) calls)
                         0)))
              (edger-right)
              (should (eq (selected-window) right))
              (should (equal (caar calls) (list edger-executable nil nil nil "cross" "clear")))
              (setq calls nil)
              (edger-right)
              (should (equal (car calls)
                             (list (list edger-executable nil nil nil "cross" "right")
                                   "/tmp/herdr.sock" "w1:p2")))
              (edger-left)
              (should (eq (selected-window) left))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)
        (set-frame-parameter frame 'edger-herdr-socket-path nil)))))

(ert-deftest edger-tmux-frame-crosses-session-edge ()
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)) calls)
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-tmux-pane-id "%3")
            (set-frame-parameter frame 'edger-tmux-socket "/tmp/tmux-test,1,0")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args)
                         (push (list args (getenv "TMUX") (getenv "TMUX_PANE")
                                     (getenv "EDGER_BACKEND")) calls)
                         0)))
              (edger-down)
              (should (equal (car calls)
                             (list (list edger-executable nil nil nil "cross" "down")
                                   "/tmp/tmux-test,1,0" "%3" "tmux")))))
        (set-frame-parameter frame 'edger-tmux-pane-id nil)
        (set-frame-parameter frame 'edger-tmux-socket nil)))))

(ert-deftest edger-crosses-regardless-of-axis-splits ()
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)) calls)
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "p1")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args) (push args calls) 0)))
              (dolist (direction '(("left" . edger-left) ("right" . edger-right)
                                   ("up" . edger-up) ("down" . edger-down)))
                (funcall (cdr direction))
                (should (equal (last (car calls) 2) (list "cross" (car direction)))))
              (let ((top (selected-window)) (bottom (split-window-below)))
                (select-window bottom)
                (edger-down)
                (should (equal (last (car calls) 2) '("cross" "down")))
                (edger-right)
                (should (equal (last (car calls) 2) '("cross" "right")))
                (select-window top)
                (edger-up)
                (should (equal (last (car calls) 2) '("cross" "up"))))
              (delete-other-windows)
              (let ((left (selected-window)) (right (split-window-right)))
                (select-window left)
                (edger-left)
                (should (equal (last (car calls) 2) '("cross" "left")))
                (select-window right)
                (edger-right)
                (should (equal (last (car calls) 2) '("cross" "right"))))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)))))

(ert-deftest edger-actions-stay-local-then-cross ()
  (should-not (fboundp 'edger-tab))
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)) calls)
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "p1")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args) (push args calls) 0)))
              (edger-resize-left)
              (should (equal (car calls) (list edger-executable nil nil nil "cross" "resize" "left")))
              (setq calls nil)
              (edger-vertical)
              (let ((width (window-total-width)))
                (edger-resize-left)
                (should (/= width (window-total-width)))
                (should (equal (mapcar (lambda (call) (nth 5 call)) calls)
                               '("clear" "clear"))))
              (edger-close)
              (should (equal (nth 5 (car calls)) "clear"))
              (edger-close)
              (should (equal (car calls) (list edger-executable nil nil nil "cross" "close")))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)))))

(ert-deftest edger-graphical-frame-stays-local ()
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "w1:p2")
            (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                      ((symbol-function 'call-process)
                       (lambda (&rest _) (ert-fail "Unexpected multiplexer call"))))
              (should-error (edger-left))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)))))
