;;; edger-test.el --- Focused editor edge tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'edger)

(ert-deftest edger-local-then-cross ()
  (save-window-excursion
    (delete-other-windows)
    (let* ((left (selected-window))
           (right (split-window-right))
           (frame (selected-frame))
           calls)
      (should (file-executable-p edger-executable))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "w1:p2")
            (set-frame-parameter frame 'edger-herdr-socket-path "/tmp/herdr.sock")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args)
                         (push (list args (getenv "HERDR_SOCKET_PATH")
                                     (getenv "HERDR_PANE_ID")) calls)
                         0)))
              (edger-right)
              (should (eq (selected-window) right))
              (should (equal (caar calls) (list edger-executable nil nil nil "cross" "clear")))
              (setq calls nil)
              (edger-right)
              (should (equal (car calls)
                             (list (list edger-executable nil nil nil "cross" "right")
                                   "/tmp/herdr.sock" "w1:p2")))
              (edger-left)
              (should (eq (selected-window) left))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)
        (set-frame-parameter frame 'edger-herdr-socket-path nil)))))

(ert-deftest edger-actions-stay-local-then-cross ()
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)) calls)
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "p1")
            (cl-letf (((symbol-function 'call-process)
                       (lambda (&rest args) (push args calls) 0)))
              (edger-resize-left)
              (should (equal (car calls) (list edger-executable nil nil nil "cross" "resize" "left")))
              (setq calls nil)
              (edger-vertical)
              (let ((width (window-total-width)))
                (edger-resize-left)
                (should (/= width (window-total-width)))
                (should (equal (mapcar (lambda (call) (nth 5 call)) calls)
                               '("clear" "clear"))))
              (edger-close)
              (should (equal (nth 5 (car calls)) "clear"))
              (edger-close)
              (should (equal (car calls) (list edger-executable nil nil nil "cross" "close")))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)))))

(ert-deftest edger-graphical-frame-stays-local ()
  (save-window-excursion
    (delete-other-windows)
    (let ((frame (selected-frame)))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'edger-herdr-pane-id "w1:p2")
            (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
                      ((symbol-function 'call-process)
                       (lambda (&rest _) (ert-fail "Unexpected multiplexer call"))))
              (should-error (edger-left))))
        (set-frame-parameter frame 'edger-herdr-pane-id nil)))))
