vim.opt.rtp:prepend(vim.fn.getcwd())
vim.env.HERDR_PANE_ID = "p1"
require("edger").setup({ keymaps = false, bin = vim.env.EDGER_TEST_BIN,
  actions = { horizontal = "u", vertical = "i", close = "w", tab = "t" } })
vim.cmd.vsplit()
local left = vim.api.nvim_get_current_win()
vim.cmd.EdgerRight()
assert(vim.api.nvim_get_current_win() ~= left, "Neovim should move internally first")
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[1] == "cross clear", "Local movement should clear armed state")
vim.cmd.EdgerRight()
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[2] == "cross right", "Vertical split should cross at its edge")
vim.cmd.only()
vim.cmd.EdgerResizeLeft()
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[3] == "cross resize left", "Resize without split should cross")
vim.cmd.EdgerVertical()
local width = vim.api.nvim_win_get_width(0)
vim.cmd.EdgerResizeLeft()
assert(vim.api.nvim_win_get_width(0) ~= width, "Resize with split should stay local")
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[4] == "cross clear", "Local resize should clear armed state")
vim.cmd.EdgerClose()
assert(#vim.api.nvim_tabpage_list_wins(0) == 1, "Close should remove a local split")
vim.cmd.EdgerHorizontal()
local height = vim.api.nvim_win_get_height(0)
vim.cmd.EdgerResizeUp()
assert(vim.api.nvim_win_get_height(0) ~= height, "Horizontal split should resize locally")
vim.cmd.EdgerClose()
vim.cmd.EdgerClose()
local calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross close", "Last window should close pane")
vim.cmd.tabnew()
vim.cmd.tabnew()
vim.cmd.EdgerVertical()
vim.cmd.EdgerClose()
assert(#vim.api.nvim_tabpage_list_wins(0) == 1 and #vim.api.nvim_list_tabpages() == 3,
  "Close should remove an editor split before tabs")
vim.cmd.EdgerClose()
assert(#vim.api.nvim_list_tabpages() == 2, "Close should remove current editor tab")
vim.cmd.EdgerClose()
assert(#vim.api.nvim_list_tabpages() == 1, "Close should keep the last editor tab")
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross clear", "Closing an editor tab should clear pending state")
vim.cmd.EdgerClose()
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross close", "Last editor tab should close multiplexer pane")
assert(vim.fn.exists(":EdgerTab") == 0, "Removed tab command should not exist")
vim.cmd.EdgerRight()
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross right", "Unsplit tab should cross immediately")
vim.cmd.split()
vim.cmd.EdgerRight()
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross right", "Horizontal split should not gate sideways exit")
vim.cmd.wincmd("j")
vim.cmd.EdgerDown()
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross down", "Horizontal split should cross at its edge")
vim.env.HERDR_PANE_ID = nil
vim.env.TMUX_PANE = "%1"
vim.env.TMUX = "/tmp/tmux-test,1,0"
vim.cmd.EdgerDown()
calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross down", "Neovim should cross a tmux session edge")
require("edger").setup({ bin = vim.env.EDGER_TEST_BIN })
assert(vim.fn.maparg("<M-h>", "n") ~= "", "Alt navigation should be the default")
assert(vim.fn.maparg("<M-H>", "n") ~= "", "Alt resize should be the default")
assert(vim.fn.maparg("<M-u>", "n") ~= "", "Alt horizontal split should be the default")
assert(vim.fn.maparg("<M-i>", "n") ~= "", "Alt vertical split should be the default")
assert(vim.fn.maparg("<M-w>", "n") ~= "", "Alt close should be the default")
require("edger").setup({ modifier = "C", actions = { horizontal = "s", vertical = "v", close = "q" },
  bin = vim.env.EDGER_TEST_BIN })
assert(vim.fn.maparg("<C-s>", "n") ~= "", "Custom split key should be mapped")
assert(vim.fn.maparg("<C-q>", "n") ~= "", "Custom close key should be mapped")
vim.cmd.qa({ bang = true })
