vim.opt.rtp:prepend(vim.fn.getcwd())
vim.env.HERDR_PANE_ID = "p1"
require("edger").setup({ keymaps = false, bin = vim.env.EDGER_TEST_BIN })
vim.cmd.vsplit()
local left = vim.api.nvim_get_current_win()
vim.cmd.EdgerRight()
assert(vim.api.nvim_get_current_win() ~= left, "Neovim should move internally first")
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[1] == "cross clear", "Local movement should clear armed state")
vim.cmd.EdgerRight()
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[2] == "cross right", "Edge should cross")
vim.cmd.only()
vim.cmd.EdgerResizeLeft()
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[3] == "cross resize left", "Resize without split should cross")
vim.cmd.EdgerVertical()
local width = vim.api.nvim_win_get_width(0)
vim.cmd.EdgerResizeLeft()
assert(vim.api.nvim_win_get_width(0) ~= width, "Resize with split should stay local")
assert(vim.fn.readfile(vim.env.EDGER_TEST_LOG)[4] == "cross clear", "Local resize should clear armed state")
vim.cmd.EdgerClose()
assert(#vim.api.nvim_tabpage_list_wins(0) == 1, "Close should remove a local split")
vim.cmd.EdgerHorizontal()
local height = vim.api.nvim_win_get_height(0)
vim.cmd.EdgerResizeUp()
assert(vim.api.nvim_win_get_height(0) ~= height, "Horizontal split should resize locally")
vim.cmd.EdgerClose()
vim.cmd.EdgerClose()
local calls = vim.fn.readfile(vim.env.EDGER_TEST_LOG)
assert(calls[#calls] == "cross close", "Last window should close pane")
vim.cmd.EdgerTab()
assert(vim.fn.tabpagenr("$") == 2, "Tab should open in Neovim")
vim.cmd.qa({ bang = true })
